#spring.application.name=api-gateway
#<<<<<<< HEAD
#<<<<<<< HEAD
#spring.main.web-application-type=reactive
##eureka.instance.hostname=localhost
##eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#logging.level.root=INFO
#logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO
#logging.level.org.springframework.cloud.gateway=TRACE
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:3000
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
## Order
## spring.cloud.gateway.routes[0].id=order-service
## spring.cloud.gateway.routes[0].uri=http://order-service:8002
## spring.cloud.gateway.routes[0].predicates[0]=Path=/api/order/**
#
## Cart
#spring.cloud.gateway.routes[0].id=cart-service
#spring.cloud.gateway.routes[0].uri=http://localhost:8003
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/cart/**
#
## Catch-all phải để cuối
#<<<<<<< HEAD
#spring.cloud.gateway.routes[1].id=marketplace-platform
#spring.cloud.gateway.routes[1].uri=http://localhost:8001
#spring.cloud.gateway.routes[1].predicates[0]=Path=/**
#server.port=8000
#=======
#spring.cloud.gateway.routes[2].id=maketplace-platform
#spring.cloud.gateway.routes[2].uri=http://localhost:8000
#spring.cloud.gateway.routes[2].predicates[0]=Path=/**
#server.port=8001
#=======
#=======
#>>>>>>> 34b7cded3cfabcb6ca72c99c60e1febe5f5520e9
#spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
#spring.main.web-application-type=reactive
##eureka.instance.hostname=localhost
##eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#logging.level.root=INFO
#logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO
#logging.level.org.springframework.cloud.gateway=TRACE
##spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:3000
##spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
##spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
##spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
#
#spring.cloud.gateway.routes[0].id=cart-service
#spring.cloud.gateway.routes[0].uri=http://cart-service:8003
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/cart/**
#
#spring.cloud.gateway.routes[1].id=order-service
#spring.cloud.gateway.routes[1].uri=http://order-service:8002
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**
#
#spring.cloud.gateway.routes[2].id=logistic-service
#spring.cloud.gateway.routes[2].uri=http://logistic-service:8007
#spring.cloud.gateway.routes[2].predicates[0]=Path=/api/logistics/**
#
## Catch-all must remain last
#spring.cloud.gateway.routes[3].id=marketplace-platform
#spring.cloud.gateway.routes[3].uri=http://ecommerce-backend:8080
#spring.cloud.gateway.routes[3].predicates[0]=Path=/**
#
#server.port=8000
#<<<<<<< HEAD
#>>>>>>> b1e61f071ca45b7aa5c116f8b8285a226bed233e
#>>>>>>> 2303dbea4457761743ead14c44865db12e8d57c3
#=======
#>>>>>>> 34b7cded3cfabcb6ca72c99c60e1febe5f5520e9
#
#
#
#
#


spring.application.name=api-gateway
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
spring.main.web-application-type=reactive
#eureka.instance.hostname=localhost
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE

spring.cloud.gateway.routes[0].id=cart-service
spring.cloud.gateway.routes[0].uri=http://cart-service:8003
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/cart/**

spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=http://order-service:8002
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**

spring.cloud.gateway.routes[2].id=logistic-service
spring.cloud.gateway.routes[2].uri=http://logistic-service:8007
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/logistics/**


spring.cloud.gateway.routes[3].id=payment-service
spring.cloud.gateway.routes[3].uri=http://payment-service:8008
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/payments/**

# Catch-all must remain last
spring.cloud.gateway.routes[4].id=marketplace-platform
spring.cloud.gateway.routes[4].uri=http://ecommerce-backend:8080
spring.cloud.gateway.routes[4].predicates[0]=Path=/**

server.port=8000

# Allow large multipart uploads (images/videos) to pass through gateway
spring.codec.max-in-memory-size=100MB
