
spring.application.name=api-gateway
spring.main.web-application-type=reactive
#eureka.instance.hostname=localhost
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_FIRST
spring.cloud.compatibility-verifier.enabled=false
spring.cloud.gateway.routes[0].id=cart-service

#spring.cloud.gateway.routes[0].uri=http://localhost:8003

spring.cloud.gateway.routes[0].uri=http://localhost:8003
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/cart/**

spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=http://localhost:8002
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**


spring.cloud.gateway.routes[2].id=logistic-service
spring.cloud.gateway.routes[2].uri=http://localhost:8007
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/logistics/**



spring.cloud.gateway.routes[3].id=payment-service
spring.cloud.gateway.routes[3].uri=http://localhost:8008
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/payments/**

# Catch-all phải để cuối

spring.cloud.gateway.routes[4].id=marketplace-platform
spring.cloud.gateway.routes[4].uri=http://localhost:8001
spring.cloud.gateway.routes[4].predicates[0]=Path=/**

server.port=8000

# Allow large multipart uploads (images/videos) to pass through gateway
spring.codec.max-in-memory-size=100MB
