

spring.application.name=api-gateway
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
spring.main.web-application-type=servlet
#eureka.instance.hostname=localhost
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE

service.order.url=http://order-service:8002
service.cart.url=http://cart-service:8003
service.logistic.url=http://logistic-service:8007
service.payment.url=http://payment-service:8008
service.stock.url=http://stock-service:8009
service.marketplace.url=http://ecommerce-backend:8080
app.jwt.secret=${JWT_SECRET}
spring.security.oauth2.resourceserver.jwt.secret=${app.jwt.secret}

server.port=8000

# Allow large multipart uploads (images/videos) to pass through gateway
spring.codec.max-in-memory-size=300MB
