spring.application.name=api-gateway
spring.main.web-application-type=reactive
#eureka.instance.hostname=localhost
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
# Order
# spring.cloud.gateway.routes[0].id=order-service
# spring.cloud.gateway.routes[0].uri=http://order-service:8002
# spring.cloud.gateway.routes[0].predicates[0]=Path=/api/order/**

# Cart
spring.cloud.gateway.routes[0].id=cart-service
spring.cloud.gateway.routes[0].uri=http://cart-service:8003
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/cart/**

spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=http://order-service:8002
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/order/**

# Catch-all phải để cuối
spring.cloud.gateway.routes[2].id=marketplace-platform
spring.cloud.gateway.routes[2].uri=http://ecommerce-backend:8001
spring.cloud.gateway.routes[2].predicates[0]=Path=/**
server.port=8000