spring.application.name=order-service

#spring.kafka.bootstrap-servers=broker:9092
spring.kafka.bootstrap-servers=broker:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer 
spring.kafka.topic.name=order_created
spring.kafka.producer.properties.spring.json.add.type.headers=false



#spring.datasource.url=${DATABASE_URL}
#spring.datasource.username=${DATABASE_USERNAME}
#spring.datasource.password=${DATABASE_PASSWORD}



	spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=true


server.port=8002