spring.datasource.url=jdbc:sqlserver://103.90.225.130:1433;databaseName=ProductDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Thoaivip@13
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver




mysql.host=localhost
mysql.port=3306
mysql.database=ecommerce
mysql.username=root
mysql.password=123456







server.port=8000


