<<<<<<< HEAD

spring.application.name=marketplace-platform
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
mysql.host=localhost
mysql.port=3306
mysql.database=ecommerce
mysql.username=root
mysql.password=123456
=======
#mysql.host=localhost
#mysql.port=3306
#mysql.database=ecommerce
#mysql.username=root
#mysql.password=123456
#
#
#spring.datasource.url=jd*********************
#spring.datasource.username=a****************
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#
#cloudinary.cloud-name=${CLOUDINARY_CLOUD_N AME}
#cloudinary.api-key=${CLOUDINARY_API_KEY}
#cloudinary.api-secret=${CLOUDINARY_API_SECRET}
>>>>>>> 377c2dbc919dfe1d16c685e1373a269a2ffe2115

cloudinary.cloud-name=dizx3mbgw
cloudinary.api-key=596145745363745
cloudinary.api-secret=f2oII0CnOjrXsGpIXhJ1CLE3EGw

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}








	
vnpay.tmnCode=WK7FXXYK
vnpay.hashSecret=67KQXGHU4ULJWQLBV1I7RX3JWSO2C7KE
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#vnpay.returnUrl=http://localhost:8000/payment/vnpay_return
vnpay.returnUrl=http://localhost:8000/payment/vnpay_return	







server.port=8001























































