spring.application.name=logistic-service


spring.kafka.consumer.bootstrap-servers=broker:9092
#ng.kafka.listener.concurrency= 3
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
#spring.kafka.consumer.bootstrap-servers=broker:9092
spring.kafka.consumer.group-id=logistic-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer 
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=logistic_service.com.dto.OrderCreatedEvent
spring.kafka.topic.name=order_created



spring.kafka.producer.bootstrap-servers=broker:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
 
spring.datasource.url=${DATABASE_URL}?serverTimezone=Asia/Ho_Chi_Minh&useUnicode=true&characterEncoding=utf8&autoReconnect=true
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.hikari.data-source-properties.serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.hikari.data-source-properties.connectionTimeZone=Asia/Ho_Chi_Minh
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8007
logistics.fee.provider.url=${LOGISTICS_FEE_PROVIDER_URL:}
logistics.fee.provider.token=${LOGISTICS_FEE_PROVIDER_TOKEN:}
