

spring.application.name=cart-service

# Database configuration


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


<<<<<<< HEAD
# JPA configuration


# Database configuration
=======

# Database configuration	
>>>>>>> a1ca836ab366b9e638f7e8f5f45978e34bac9691





server.port=8003