<<<<<<< HEAD
spring.application.name=cart-service
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
=======


spring.application.name=cart-service

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
# Database configuration


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}




spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver







# Database configuration	




>>>>>>> b1e61f071ca45b7aa5c116f8b8285a226bed233e

server.port=8003