
spring.application.name=cart-service


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.hikari.data-source-properties.serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.hikari.data-source-properties.connectionTimeZone=Asia/Ho_Chi_Minh

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

<<<<<<< HEAD

<<<<<<< HEAD
<<<<<<< HEAD
# JPA configuration
=======
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
>>>>>>> 93c8346aa5bbe8c27002b7a82db1b68b810dc7d9


# Database configuration
=======

<<<<<<< HEAD
# Database configuration	
>>>>>>> a1ca836ab366b9e638f7e8f5f45978e34bac9691
=======





# Database configuration	
>>>>>>> e4dd6569ac30ad63e61404155328fc3d319dbff5
=======
>>>>>>> 93c8346aa5bbe8c27002b7a82db1b68b810dc7d9





server.port=8003