import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";
import StoreProvider from "./StoreProvider";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en" className="mdl-js">
        <head>
          <link
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
            rel="stylesheet"
          />
          <style>
            {`     :root {
                --primary: #2b8cee;
                --primary-dark: #1a6cb8;
            }
            
            body {
                font-family: "Plus Jakarta Sans", sans-serif;
                background-color: #f6f7f8;
            }
            
            .utility-bar {
                background-color: var(--primary);
                color: white;
                font-size: 0.75rem;
                padding: 0.25rem 0;
            }
            
            .utility-bar a {
                color: white;
                text-decoration: none;
            }
            
            .utility-bar a:hover {
                opacity: 0.8;
            }
            
            .search-box {
                background-color: #f0f2f4;
                border: 2px solid transparent;
                border-radius: 0.5rem;
                transition: all 0.3s;
            }
            
            .search-box:focus-within {
                border-color: rgba(43, 140, 238, 0.2);
                box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            }
            
            .search-box input {
                background: transparent;
                border: none;
                outline: none;
            }
            
            .search-box input:focus {
                box-shadow: none;
            }
            
            .btn-search {
                background-color: var(--primary);
                color: white;
                border-radius: 0.375rem;
            }
            
            .btn-search:hover {
                background-color: var(--primary-dark);
            }
            
            .cart-badge {
                position: absolute;
                top: -5px;
                right: -5px;
                background-color: #dc3545;
                color: white;
                font-size: 0.625rem;
                font-weight: bold;
                padding: 0.125rem 0.375rem;
                border-radius: 50px;
                border: 2px solid white;
            }
            
            .banner-main {
                height: 280px;
                background-size: cover;
                background-position: center;
                border-radius: 0.5rem;
                position: relative;
            }
            
            .banner-side {
                height: 136px;
                background-size: cover;
                background-position: center;
                border-radius: 0.5rem;
                position: relative;
            }
        }`}
          </style>
        </head>
        <body className={`index-page`} suppressHydrationWarning>
          <NextTopLoader
            color="#ee4d2d"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
            zIndex={9999}
          />
          <main className="main">{children}</main>

          {/* <Script src="/assets/js/main.js" strategy="afterInteractive" /> */}
        </body>
      </html>
    </StoreProvider>
  );
}
