import "bootstrap/dist/css/bootstrap.min.css"; // JS (dropdown, offcanvas, modal...)
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Script from "next/script";
import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const role = cookieStore.get("role")?.value;
  console.log("Role: " + role);
  if (role == "admin") return redirect("/login");
  return (
    <>
      <header
        id="header"
        className="header d-flex align-items-center sticky-top"
      >
        <h1>Navbar</h1>
      </header>
      <main className="main">{children}</main>
      <Script src="/assets/js/main.js" strategy="afterInteractive" />
    </>
  );
}
