name: Deploy marketfrontend

on:
  push:
    branches: ["main"]
    paths:
      - "marketfrontend/**"

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      context_path: ./marketfrontend
      image_name: ecommerce-frontend
      service_name: marketfrontend
    secrets: inherit
