name: Frontend CI

on:
  push:
<<<<<<< HEAD
    branches: [ develop, feature/*,Diep1 ]
=======
<<<<<<< HEAD
    branches: [ develop, feature/*,Diep ]
=======
    branches: [ develop, feature/*,Diep1 ]
>>>>>>> b1e61f071ca45b7aa5c116f8b8285a226bed233e
>>>>>>> 2303dbea4457761743ead14c44865db12e8d57c3
    paths:
      - "marketfrontend/**"
  pull_request:
    paths:
      - "marketfrontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Next.js
        working-directory: marketfrontend
        run: |
          npm install
          npm run build
